replicaCount: 1

webapp:
  name: rda-tds
  group: rda-tds
  path: /
  tls:
    fqdn: tds.nickknows.net
    secretName: incommon-cert-tds
  container: 
    image: docker.io/potatofever/rda-tds:sha-4851539
    port: 8080
    memory: 12G
    cpu: 5
  logs: 
    name: rda-logs
    image: docker.io/potatofever/rda-logs:sha-4dfa09c
    port: 8080
    memory: 2G
    cpu: 1
  volume:
    fs:
      name: tds-persist
      size: 10Gi
      mountPath: /data/TDSIndexFiles/data/rda/data # /data/TDSIndexFiles
  volume2:
    fs:
      name: logs-persist
      size: 5Gi
      mountPath: /usr/local/tomcat/logs